---
# file: tasks/main.yml

- name: Ping hosts
  ansible.builtin.ping:

- name: Create the Node Exporter group
  ansible.builtin.group:
    name: "{{ node_exporter_group }}"
    state: present
    system: true

- name: Create a user for Node Exporter
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    system: true
    shell: "/bin/false"
    state: present

- name: Download Node Exporter
  ansible.builtin.get_url:
    checksum: "sha256:{{ node_exporter_sha256 }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_release }}.tar.gz"
    mode: u=rwx,g=rx,o=rx
    owner: "{{ node_exporter_user }}"
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_release }}.tar.gz"
  check_mode: false

- name: Unarchive Node Exporter
  ansible.builtin.unarchive:
    dest: /usr/local/bin
    owner: "{{ node_exporter_user }}"
    remote_src: true
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_release }}.tar.gz"

- name: Install systemd service for Node Exporter
  ansible.builtin.template:
    dest: /lib/systemd/system/node_exporter.service
    group: root
    mode: u=rw,g=r,o=r
    owner: root
    src: node_exporter.service.j2
  notify: Restart NodeExporter
