---
# file: handlers/main.yml

- name: Restart NodeExporter
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    masked: false
    name: node-exporter
    scope: system
    state: restarted
