---

dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: mol-ne-ubuntu22
    image: jrei/systemd-ubuntu:jammy
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: /lib/systemd/systemd

provisioner:
  name: ansible

scenario:
  name: default

verifier:
  name: ansible
